version: '3'
services: 
    db:
        image: 'postgres:latest'
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: authenticator
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    app:
        container_name: authenticator
        restart: always
        build: .
        ports:
            - "5432:5432"
        depends_on:
            - db